### ISSUE TITLE
position prop default

### ISSUE THREAD

**Issue by pungggi** [ctxhou/react-poppop#54]
centerCenter should be the default in my opinion

**Comment by ctxhou** [comment]
Yes, in most of the use cases we usually use `centerCenter` as default. But I am afraid that changing the default value would affect the existing users.

Anyway, it is just a difference between one props. 
Thanks for the suggestion 😄

**Comment by pungggi** [comment]
sure I understand, but bumping a version up to say 1.6.0 and update the docs should do the trick.

With this a user of the library is warned that minor non-breaking changes are expected.
